const {
  BEACH_WEATHER_KEY,
  API_URL_BASE,
  OCEAN_DATA_KEY,
  LIVING_WEATHER_KEY,
  MEDIUM_FORECAST_KEY,
  SHORT_FORECAST_KEY,
  AIR_QUALITY_KEY,
  NAVER_ANALYTICS_KEY,
  GA_TRACKING_ID,
} = process.env;

module.exports = {
  API_URL_BASE,
  BEACH_WEATHER_KEY,
  OCEAN_DATA_KEY,
  LIVING_WEATHER_KEY,
  MEDIUM_FORECAST_KEY,
  SHORT_FORECAST_KEY,
  AIR_QUALITY_KEY,
  NAVER_ANALYTICS_KEY,
  GA_TRACKING_ID,
};
